sudo: false
language: python
python:
  - "3.8"
install:
  - pip install poetry
  - poetry install
script: python -m coverage run --source=toapi -m pytest && coverage report

after_success:
  - codecov
branches:
  only:
    - master